run:
  tests: false
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor
linters:
  enable:
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
  disable-all: true
