run:
  tests: false
  timeout: 5m
  output:
    format: github-actions
  skip-dirs:
    - vendor
linters:
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - gas
  - errcheck
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - revive
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - megacheck
  - nakedret
  - rowserrcheck
  - exportloopref
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  disable-all: true
