run:
  tests: false
  timeout: 5m
linters:
  enable:
  - bodyclose
  - dogsled
  - dupl
  - errcheck
  - copyloopvar
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosec
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  disable-all: true
issues:
  exclude-dirs:
    - vendor