services:

  test1:
  - server: http://127.0.0.1:7070
    ping: /api/v1/ping
    method: GET
    weight: 1
  - server: http://localhost:7070
    ping: /api/v1/ping
    method: GET
    weight: 1

no_node:

  message: >
    <!doctype html>
    <head>
        <meta http-equiv="content-type" content="text/html;charset=utf-8">
        <title>See README.md</title>
        <style>
          body { text-align: center; padding: 150px; }
          body { font: 20px Helvetica, sans-serif; color: #333; }
          article { display: block; width: 100%; margin: 0 auto; }
          a { color: #dc8100; text-decoration: none; }
          a:hover { color: #333; text-decoration: none; }
        </style>
    </head>

    <article>
        <h2>Please see <a href="https://github.com/umputun/rlb-stats/">https://github.com/umputun/rlb-stats/</a> for instructions</h2>
    </article>
